name: Create Package Index

on:
  workflow_dispatch:
  workflow_call:

jobs:
  create_index:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requests
        run: pip install requests

      - name: Create packages index
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPO_NAME: ${{ github.repository }}
        run: python create_index.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: create_index
    permissions:
      pages: write
      id-token: write
    runs-on: self-hosted

    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
